import type { Campaign } from '@/types'
import { money } from '@/lib/money'

const daysFromNow = (days: number): string => {
  const d = new Date()
  d.setDate(d.getDate() + days)
  return d.toISOString()
}

const ISO_NOW = new Date().toISOString()

export const SEED_CAMPAIGNS: readonly Campaign[] = [
  {
    id: 'cmp-1',
    slug: 'lampara-modular-eco',
    title: 'Lámpara modular eco-friendly',
    summary: 'Iluminación reciclable con módulos magnéticos para tu espacio.',
    description:
      '# Lámpara modular\n\nUn sistema de iluminación que crece contigo. Cada módulo es 100% reciclable y se conecta magnéticamente sin tornillos.',
    categoryId: 'cat-tech',
    location: { city: 'Ciudad de México', country: 'México' },
    tags: ['hogar', 'sostenible', 'diseño'],
    goal: money(15_000_00),
    raised: money(12_400_00),
    goalType: 'fixed',
    backersCount: 87,
    startDate: daysFromNow(-20),
    endDate: daysFromNow(10),
    durationDays: 30,
    status: 'active',
    featured: true,
    coverImageUrl: 'https://picsum.photos/seed/cmp1/800/450',
    gallery: ['https://picsum.photos/seed/cmp1a/800/450'],
    creatorId: 'usr-creator-1',
    createdAt: daysFromNow(-30),
    updatedAt: ISO_NOW,
    approvedAt: daysFromNow(-21),
  },
  {
    id: 'cmp-2',
    slug: 'mural-comunitario-barrio-azul',
    title: 'Mural comunitario Barrio Azul',
    summary: 'Pintemos juntos el mural más grande del barrio.',
    description:
      'Una iniciativa vecinal para transformar la fachada de la plaza con un mural participativo.',
    categoryId: 'cat-community',
    location: { city: 'Buenos Aires', country: 'Argentina' },
    tags: ['arte público', 'comunidad'],
    goal: money(3_000_00),
    raised: money(3_450_00),
    goalType: 'flexible',
    backersCount: 142,
    startDate: daysFromNow(-45),
    endDate: daysFromNow(-2),
    durationDays: 45,
    status: 'successful',
    featured: false,
    coverImageUrl: 'https://picsum.photos/seed/cmp2/800/450',
    gallery: [],
    creatorId: 'usr-creator-1',
    createdAt: daysFromNow(-50),
    updatedAt: daysFromNow(-2),
    approvedAt: daysFromNow(-46),
  },
  {
    id: 'cmp-3',
    slug: 'curso-programacion-rural',
    title: 'Programación para escuelas rurales',
    summary: 'Llevamos clases de programación a 5 escuelas en zonas rurales.',
    description:
      'Material didáctico, laptops reacondicionadas y 6 meses de clases para 120 estudiantes.',
    categoryId: 'cat-edu',
    location: { city: 'Lima', country: 'Perú' },
    tags: ['educación', 'tecnología'],
    goal: money(25_000_00),
    raised: money(5_200_00),
    goalType: 'fixed',
    backersCount: 41,
    startDate: daysFromNow(-10),
    endDate: daysFromNow(35),
    durationDays: 45,
    status: 'active',
    featured: true,
    coverImageUrl: 'https://picsum.photos/seed/cmp3/800/450',
    gallery: [],
    creatorId: 'usr-creator-2',
    createdAt: daysFromNow(-20),
    updatedAt: ISO_NOW,
    approvedAt: daysFromNow(-11),
  },
  {
    id: 'cmp-4',
    slug: 'libro-fotografia-andina',
    title: 'Libro de fotografía andina',
    summary: 'Recopilación de fotografías de 10 años recorriendo los Andes.',
    description: 'Un libro de tapa dura con 200 fotografías y testimonios de comunidades andinas.',
    categoryId: 'cat-art',
    location: { city: 'Cusco', country: 'Perú' },
    tags: ['fotografía', 'libro'],
    goal: money(8_000_00),
    raised: money(2_100_00),
    goalType: 'fixed',
    backersCount: 28,
    startDate: daysFromNow(-40),
    endDate: daysFromNow(-5),
    durationDays: 35,
    status: 'failed',
    featured: false,
    coverImageUrl: 'https://picsum.photos/seed/cmp4/800/450',
    gallery: [],
    creatorId: 'usr-creator-1',
    createdAt: daysFromNow(-45),
    updatedAt: daysFromNow(-5),
    approvedAt: daysFromNow(-41),
  },
  {
    id: 'cmp-5',
    slug: 'reforestacion-manglar',
    title: 'Reforestación de manglar costero',
    summary: 'Plantamos 10,000 mangles en la costa de El Salvador.',
    description: 'Programa de reforestación con voluntarios locales y monitoreo a 3 años.',
    categoryId: 'cat-env',
    location: { city: 'La Libertad', country: 'El Salvador' },
    tags: ['medio ambiente', 'reforestación'],
    goal: money(12_000_00),
    raised: money(0),
    goalType: 'fixed',
    backersCount: 0,
    startDate: daysFromNow(2),
    endDate: daysFromNow(62),
    durationDays: 60,
    status: 'pending_review',
    featured: false,
    coverImageUrl: 'https://picsum.photos/seed/cmp5/800/450',
    gallery: [],
    creatorId: 'usr-creator-1',
    createdAt: daysFromNow(-3),
    updatedAt: daysFromNow(-3),
  },
  {
    id: 'cmp-6',
    slug: 'app-finanzas-personales',
    title: 'App de finanzas personales para latinoamérica',
    summary: 'Borrador en construcción.',
    description: '',
    categoryId: 'cat-tech',
    location: { city: 'Santiago', country: 'Chile' },
    tags: [],
    goal: money(20_000_00),
    raised: money(0),
    goalType: 'fixed',
    backersCount: 0,
    startDate: daysFromNow(7),
    endDate: daysFromNow(37),
    durationDays: 30,
    status: 'draft',
    featured: false,
    coverImageUrl: '',
    gallery: [],
    creatorId: 'usr-backer-3',
    createdAt: daysFromNow(-1),
    updatedAt: daysFromNow(-1),
  },
] as const
