import type { Reward } from '@/types'
import { money } from '@/lib/money'

export const SEED_REWARDS: readonly Reward[] = [
  {
    id: 'rwd-1',
    campaignId: 'cmp-1',
    title: 'Módulo inicial',
    description: 'Un módulo base + adaptador de pared.',
    minAmount: money(45_00),
    estimatedDelivery: '2026-08-01',
    stock: 100,
    claimed: 38,
    order: 0,
  },
  {
    id: 'rwd-2',
    campaignId: 'cmp-1',
    title: 'Pack hogar',
    description: '4 módulos + soportes magnéticos + guía de instalación.',
    minAmount: money(180_00),
    estimatedDelivery: '2026-08-15',
    stock: 50,
    claimed: 22,
    order: 1,
  },
  {
    id: 'rwd-3',
    campaignId: 'cmp-1',
    title: 'Edición coleccionista',
    description: '8 módulos en acabado mate + grabado personalizado.',
    minAmount: money(420_00),
    estimatedDelivery: '2026-09-01',
    stock: 20,
    claimed: 5,
    order: 2,
  },
  {
    id: 'rwd-4',
    campaignId: 'cmp-2',
    title: 'Tu nombre en el mural',
    description: 'Aparecerás en los créditos pintados del mural.',
    minAmount: money(10_00),
    claimed: 89,
    order: 0,
  },
  {
    id: 'rwd-5',
    campaignId: 'cmp-3',
    title: 'Auspicia un estudiante',
    description: 'Material y clases para un estudiante por 6 meses.',
    minAmount: money(120_00),
    estimatedDelivery: '2026-03-01',
    claimed: 14,
    order: 0,
  },
  {
    id: 'rwd-6',
    campaignId: 'cmp-4',
    title: 'Copia del libro',
    description: 'Libro firmado + envío internacional.',
    minAmount: money(60_00),
    estimatedDelivery: '2026-06-01',
    stock: 200,
    claimed: 18,
    order: 0,
  },
] as const
