import type { User } from '@/types'

const ISO_2024 = '2024-09-15T10:00:00.000Z'
const ISO_2025 = '2025-01-20T10:00:00.000Z'

export const SEED_USERS: readonly User[] = [
  {
    id: 'usr-admin-1',
    email: 'admin@fondea.app',
    name: 'Ada Admin',
    roles: ['admin'],
    location: { city: 'San Salvador', country: 'El Salvador' },
    bio: 'Administradora de la plataforma',
    avatarUrl: 'https://i.pravatar.cc/150?u=admin1',
    createdAt: ISO_2024,
  },
  {
    id: 'usr-creator-1',
    email: 'carla@fondea.app',
    name: 'Carla Creadora',
    roles: ['creator', 'backer'],
    location: { city: 'Ciudad de México', country: 'México' },
    bio: 'Diseñadora industrial trabajando en productos sostenibles.',
    avatarUrl: 'https://i.pravatar.cc/150?u=creator1',
    verifiedAt: ISO_2024,
    isNewCreator: false,
    campaignsCount: 3,
    pledgesCount: 4,
    createdAt: ISO_2024,
  },
  {
    id: 'usr-creator-2',
    email: 'cesar@fondea.app',
    name: 'César Nuevo',
    roles: ['creator'],
    location: { city: 'Lima', country: 'Perú' },
    bio: 'Primera campaña en la plataforma.',
    avatarUrl: 'https://i.pravatar.cc/150?u=creator2',
    isNewCreator: true,
    campaignsCount: 1,
    createdAt: ISO_2025,
  },
  {
    id: 'usr-backer-1',
    email: 'beto@example.com',
    name: 'Beto Backer',
    roles: ['backer'],
    location: { city: 'Buenos Aires', country: 'Argentina' },
    avatarUrl: 'https://i.pravatar.cc/150?u=backer1',
    pledgesCount: 5,
    createdAt: ISO_2024,
  },
  {
    id: 'usr-backer-2',
    email: 'bea@example.com',
    name: 'Bea Backer',
    roles: ['backer'],
    location: { city: 'Bogotá', country: 'Colombia' },
    avatarUrl: 'https://i.pravatar.cc/150?u=backer2',
    pledgesCount: 2,
    createdAt: ISO_2024,
  },
  {
    id: 'usr-backer-3',
    email: 'bruno@example.com',
    name: 'Bruno Backer',
    roles: ['backer', 'creator'],
    location: { city: 'Santiago', country: 'Chile' },
    avatarUrl: 'https://i.pravatar.cc/150?u=backer3',
    isNewCreator: true,
    pledgesCount: 1,
    campaignsCount: 0,
    createdAt: ISO_2025,
  },
] as const
